### ISSUE TITLE
Save the image in currently opened folder in Finder 

### ISSUE THREAD

**Issue by zeshanshani** [luckman212/alfredworkflows#1]
Hi, thank you for the great workflow. It already works really well.

Would it be possible to save the image in the currently opened folder in Finder? 

Thanks!

**Comment by luckman212** [comment]
Thanks, I'll see if I can find a little time to add this. What should happen if you don't have any Finder window open? Should it just save on the Desktop?

**Comment by luckman212** [comment]
@zeshanshani Please give the new 1.2.0 version a try! I implemented your feature, you just have to set `save_to_current` in the workflow variables screen to `true` (lowercase) to try it out.

<img width="495" alt="7e9b000103ec0fd7e48145eed7079be70316c3b4" src="https://user-images.githubusercontent.com/1992842/147934413-8f583d95-22c0-4a1b-9abb-662f51e570dc.png">

also, this version shows the actual thumbnail in the Alfred popup instead of the generic app icon.

**Comment by zeshanshani** [comment]
Mistaken. It's working well!

~@luckman212 that was brilliantly fast! Thank you. Unfortunately, when I load the new 1.2.0 version, I can't see any variables. Might have I done something wrong?~

![Screenshot_03_01_2022__6_14_PM](https://user-images.githubusercontent.com/4566996/147934572-450554f5-04ce-4d0d-8218-b66fc2ac64cc.jpg)

**Comment by zeshanshani** [comment]
Aah, please ignore my last comment. I downloaded wrong file. 

Amazing!! It's working absolutely perfect!! Thank you so much Luke! 💯

**Comment by luckman212** [comment]
👍 glad to help.
